def addtwo(): 
    a = 10 
    b = 20 
    print(a+b)

#calling addTwo function

addtwo()    

# a & b canot acces outside of function
#print(a) // gives error
#print(b) // gives error [NameError]